title: Christian Batista | Consultoria em TI
description: Especialista em Arquitetura de Sistemas, Infraestrutura Linux e Desenvolvimento Web Moderno em Maceió.
url: "https://christianbatista.com.br"

markdown: kramdown

# for atom feed
author:
  name: christian batista
  email: me@christianbatista.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
title: Christian Batista
markdown: kramdown

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["feed.xml", "LICENSE", "README.md", "Gemfile", "Gemfile.lock", "node_modules"]

